### ISSUE TITLE
pipenv run python -m main

### ISSUE THREAD

**Issue by ak9250** [rev3ks/Crypto-Liquid-Market-Maker#12]
getting this error when running pipenv run python -m main

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ahsenkhaliq/Crypto-Liquid-Market-Maker/main.py", line 1, in <module>
    import trading_algorithm as ta
  File "/Users/ahsenkhaliq/Crypto-Liquid-Market-Maker/trading_algorithm.py", line 2, in <module>
    import trading, subscribe, process
  File "/Users/ahsenkhaliq/Crypto-Liquid-Market-Maker/trading.py", line 1, in <module>
    import authorize, requests, config
  File "/Users/ahsenkhaliq/Crypto-Liquid-Market-Maker/authorize.py", line 1, in <module>
    import json, hmac, hashlib, time, requests, base64, config
ModuleNotFoundError: No module named 'config'
Ahsens-MacBook-Pro:Crypto-Liquid-Market-Maker ahsenkhaliq$ pipenv run python -m main
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ahsenkhaliq/Crypto-Liquid-Market-Maker/main.py", line 1, in <module>
    import trading_algorithm as ta
  File "/Users/ahsenkhaliq/Crypto-Liquid-Market-Maker/trading_algorithm.py", line 2, in <module>
    import trading, subscribe, process
  File "/Users/ahsenkhaliq/Crypto-Liquid-Market-Maker/trading.py", line 1, in <module>
    import authorize, requests, config
  File "/Users/ahsenkhaliq/Crypto-Liquid-Market-Maker/authorize.py", line 1, in <module>
    import json, hmac, hashlib, time, requests, base64, config
ModuleNotFoundError: No module named 'config'

also config.py.default was in folders not config.ini.default so i used cp config.py.default config.ini

**Comment by rev3ks** [comment]
My bad, I didn't update the readme after changing from .py to .ini. If you follow these instructions it should work. 
* `cp config.py.default config.py`
* Add GDAX API passphrase, keys, and secret to config.py

**Comment by rev3ks** [comment]
https://github.com/rev3ks/Crypto-Liquid-Market-Maker/commit/65b03dece7f8e773b1534f5d528752ccbf8c6391

**Comment by ak9250** [comment]
thanks that worked but now I get this after list trades

Listing trades, user CTRL+c to kill

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/ahsenkhaliq/Crypto-Liquid-Market-Maker/main.py", line 46, in <module>
    run_main()
  File "/Users/ahsenkhaliq/Crypto-Liquid-Market-Maker/main.py", line 28, in run_main
    trade_terms.start_ws()
  File "/Users/ahsenkhaliq/Crypto-Liquid-Market-Maker/trading_algorithm.py", line 108, in start_ws
    self.socket.start()
  File "/Users/ahsenkhaliq/Crypto-Liquid-Market-Maker/subscribe.py", line 63, in start
    asyncio.get_event_loop().run_until_complete(self.ws)  
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/Users/ahsenkhaliq/Crypto-Liquid-Market-Maker/subscribe.py", line 67, in _connect
    async with websockets.connect(self.url) as ws:
  File "/Users/ahsenkhaliq/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-ra9WOz9i/lib/python3.6/site-packages/websockets/client.py", line 386, in __aenter__
    return (yield from self)
  File "/Users/ahsenkhaliq/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-ra9WOz9i/lib/python3.6/site-packages/websockets/client.py", line 393, in __await__
    transport, protocol = yield from self._creating_connection
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 804, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 830, in _create_connection_transport
    yield from waiter
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 505, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
