### ISSUE TITLE
Websocket

### ISSUE THREAD

**Issue by rev3ks** [rev3ks/Crypto-Liquid-Market-Maker#3]
The GDAX websocket has multiple channels to subscribe to, [https://docs.gdax.com/#websocket-feed](url) It seems the best to use would be level2, match, or full. The current socket logic is in `subscribe.py` and can be run from bash as follows:

`$python -m subscribe subscribe [product_id1],[product_id2],... [channel1],[channel2],...l`

results will be printed to `./socketdata/data.txt` 

I did not do the best job of completely understanding the socket logic and have been reading more into async and treading to understand what my attempts are missing.  It seems some of the channels with less frequent subscription messages lead the websocket to disconnect. I have seen this more with ticker and match. It is likely improperly constructed logic in `subscribe.py`

Once the this is corrected, messages need to be parsed and when trades in a certain strategy execute, a `trading.adjust()` function should result with corresponding input to executed trade. Right now `adjust()` will cancel all orders in the range of trades to list, this is fine unless two strategies exist in the same pair.

**Comment by rev3ks** [comment]
Error stopping socket:`Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/will/Documents/Crypto-Trading/Crypto-Liquid-Market-Maker/subscribe.py", line 123, in <module>
    sock.start()
  File "/home/will/Documents/Crypto-Trading/Crypto-Liquid-Market-Maker/subscribe.py", line 32, in start
    asyncio.get_event_loop().run_until_complete(self.ws) 
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/will/Documents/Crypto-Trading/Crypto-Liquid-Market-Maker/subscribe.py", line 66, in start_to_send
    msg = await websocket.recv()
  File "/usr/local/lib/python3.5/dist-packages/websockets/protocol.py", line 323, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
`

**Comment by rev3ks** [comment]
When trying to handle the exception I am getting this error:

**Comment by rev3ks** [comment]
After adding a 20 second ping I believe the eof_recieved is no longer an issue.

**Comment by rev3ks** [comment]
Completed with last merge to master.
