### ISSUE TITLE
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

### ISSUE THREAD

**Issue by rev3ks** [rev3ks/Crypto-Liquid-Market-Maker#56]
While running the trader, I saw this error multiple times. The situation that leads up to it is as follows, 

1. Socket Manager receives a match for an order in the book, 
2. ThreadHandler checks the match in the Book
3. In the BookManager, Order is found
4. Order filled size is updated
5. If Order filled matches order size, order is marked as filled
6. In the ThreadHandler, Order is again checked to see if it has been marked filled
7. during this check sqlalchemy runs the following query:
```SELECT orders.exchange_id AS orders_exchange_id, orders.pair AS orders_pair, orders.side AS orders_side, orders.price AS orders_price, orders.size AS orders_size, orders.filled AS orders_filled, orders.status AS orders_status, orders.post_only AS orders_post_only, orders.id AS orders_id, orders.created_at AS orders_created_at, orders.book_id AS orders_book_id 
FROM orders 
WHERE orders.id = %(param_1)s]
[parameters: {'param_1': 57768}]
```

8. pymysql engine recieves an IOExeption from MYSQL:  (2013, 'Lost connection to MySQL server during query')

After researching this error, I cant say for cetrain what it is. The query doesnt seem to be a time out, as when I ran it from mysql, it came back without issue. 

One theory is that this query is in the query_cache and upon being updated and imidiately queried again, there is some issue where the query_cache is causing problems due to the update. 

To address the issue, add better error handling and attempt to disconnect and reconnect from the database and try again. Enable logging for mysql in and check trading logs for occurances to cross refrence to mysql. 

```2019-08-12 02:49:50,414 [INFO] trader.socket.reader: < 2019-08-12T08:49:50.870000Z - ETH-USD - trade_id: 50768950 - side: buy size: 0.07140000 price: 211.27000000
2019-08-12 02:49:50,415 [INFO] trader.socket.thread_handler: Checking book for matched trade
2019-08-12 02:49:50,742 [INFO] trader.socket.thread_handler: Matched trade is in book
2019-08-12 02:49:50,773 [ERROR] trader.socket.manager: Socket had a general exception, last message received 0.36115169525146484 seconds ago
Traceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/pi/Projects/Crypto-Liquid-Market-Maker/trader/socket/manager.py", line 121, in listen
    self.reader.new(message)
  File "/home/pi/Projects/Crypto-Liquid-Market-Maker/trader/socket/reader.py", line 31, in new
    return function_name(msg)
  File "/home/pi/Projects/Crypto-Liquid-Market-Maker/trader/socket/reader.py", line 88, in match
    self.check_book(msg)
  File "/home/pi/Projects/Crypto-Liquid-Market-Maker/trader/socket/reader.py", line 108, in check_book
    self.thread_handler.check_book_for_match(msg)
  File "/home/pi/Projects/Crypto-Liquid-Market-Maker/trader/socket/thread_handler.py", line 46, in check_book_for_match
    if order.status == "filled":
  File "/home/pi/Projects/Crypto-Liquid-Market-Maker/trader/exchange/order.py", line 106, in status
    return self._status
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 276, in __get__
    return self.impl.get(instance_state(instance), dict_)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/orm/attributes.py", line 677, in get
    value = state._load_expired(state, passive)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/orm/state.py", line 660, in _load_expired
    self.manager.deferred_scalar_loader(self, toload)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 979, in load_scalar_attributes
    only_load_props=attribute_names,
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 208, in load_on_ident
    identity_token=identity_token,
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 282, in load_on_pk_identity
    return q.one()
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3275, in one
    ret = self.one_or_none()
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3244, in one_or_none
    ret = list(self)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3317, in __iter__
    return self._execute_and_instances(context)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 3342, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2013, 'Lost connection to MySQL server during query')
[SQL: SELECT orders.exchange_id AS orders_exchange_id, orders.pair AS orders_pair, orders.side AS orders_side, orders.price AS orders_price, orders.size AS orders_size, orders.filled AS orders_filled, orders.status AS orders_status, orders.post_only AS orders_post_only, orders.id AS orders_id, orders.created_at AS orders_created_at, orders.book_id AS orders_book_id 
FROM orders 
WHERE orders.id = %(param_1)s]
[parameters: {'param_1': 57768}]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-08-12 02:49:51,141 [ERROR] trader.socket.manager: last message received 0.7087192535400391 seconds ago/nTraceback (most recent call last):
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_c
ontext
    cursor, statement, parameters, context
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 552, in do_execu
te
    cursor.execute(statement, parameters)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/connections.py", line 732, in _read_query_re
sult
    result.read()
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/connections.py", line 657, in _read_packet
    packet_header = self._read_bytes(4)
  File "/home/pi/.local/share/virtualenvs/Crypto-Liquid-Market-Maker-z1bk84NN/lib/python3.5/site-packages/pymysql/connections.py", line 707, in _read_bytes
    CR.CR_SERVER_LOST, "Lost connection to MySQL server during query")
pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')```

**Comment by rev3ks** [comment]
This issues was not solved by the above merge. Upon further investigation and QA, I have discovered the cause of this. MariaDB has a default timeout for connections in the thread pool.
```mysql> SHOW VARIABLES like "thread_pool_idle_timeout";
+--------------------------+-------+
| Variable_name            | Value |
+--------------------------+-------+
| thread_pool_idle_timeout | 60    |
+--------------------------+-------+
```
I was able to reproduce this issue by starting up the trader. Once trades were being listed I would use a separate test trading account to execute some trades that would be processed by the trader. This will create a few threads to process each match. Then once that processing of each thread was completed, I would wait one minute and create more trades with the other test account. Because the Mysql config was set to 60, the inactive thread pool connections were closed and the disconnect error was raised when the trader reached out again to grab the info it needed.
